// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the "Change Firebase Project" command.
export const firebaseConfig = {
  "apiKey": "placeholder-api-key",
  "authDomain": "placeholder-auth-domain",
  "projectId": "placeholder-project-id",
  "storageBucket": "placeholder-storage-bucket",
  "messagingSenderId": "placeholder-messaging-sender-id",
  "appId": "placeholder-app-id"
};
